name: Block Category type 5
description: 
enabled_text: false
required_text: false
enabled_link: false
enabled_image: false
css:
  -
    path: views/templates/front/blockcategory_t5/css/style.css
    priority: 200
    position: head
    server: local    
